"""
Manual translation of Fredheim recipes EN -> NO.
Hand-curated dictionaries, no API calls, no reuse of the earlier automated
translations. Preserves any user-supplied translations already in the pack.

Run:  python scripts/manual_translate.py
"""

import json
import os
import re
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = r'C:\Users\fredr\Downloads\fredheim-receoie-with-picture.json'
DST = os.path.join(ROOT, 'recipe-packs-template', 'packs',
                   'fredheim-recipes-with-pictures.json')

# Hand-translated Norwegian steps, keyed by recipe id. Loaded lazily so the
# module imports cleanly even if the file hasn't been generated yet.
_STEP_OVERRIDES_PATH = os.path.join(
    ROOT, 'scripts', '_tmp', 'step_translations_no.json'
)
try:
    with open(_STEP_OVERRIDES_PATH, encoding='utf-8') as _f:
        STEP_OVERRIDES = json.load(_f)
except FileNotFoundError:
    STEP_OVERRIDES = {}

# --------------------------------------------------------------------------
# Categories
# --------------------------------------------------------------------------
CATEGORY = {
    'Breakfast': 'Frokost',
    'Lunch': 'Lunsj',
    'Dinner': 'Middag',
    'Main': 'Middag',
    'Supper': 'Kveldsmat',
    'Snack': 'Mellommåltid',
    'Bread': 'Brød',
    'Porridge': 'Grøt',
    'Spreads': 'Pålegg',
    'Dessert': 'Dessert',
    'Soup': 'Suppe',
    'Salad': 'Salat',
    'Sauce': 'Saus',
    'Side': 'Tilbehør',
    'Other': 'Annet',
    'Drinks': 'Drikke',
    'Jams': 'Syltetøy',
    'Dressing': 'Dressing',
}

# --------------------------------------------------------------------------
# Titles — every untranslated title hand-translated
# --------------------------------------------------------------------------
TITLES = {
    'Avocado Dressing': 'Avokadodressing',
    'Baba Ghanoush - Aubergine Dip': 'Baba ganoush – auberginedipp',
    'Baked Roots': 'Ovnsbakte rotgrønnsaker',
    'Baked Sweet Potato': 'Ovnsbakt søtpotet',
    'Barley Cup Drink': 'Byggkaffedrikk',
    'Bean Pâté': 'Bønnepostei',
    'Bean Spread': 'Bønnepålegg',
    'Berry Sauce': 'Bærsaus',
    'Black Bean Stew': 'Svart bønnegryte',
    'Blissful Sprout Medley': 'Sprøtt spireblanding',
    'Blueberry Jam': 'Blåbærsyltetøy',
    'Bread Buns': 'Rundstykker',
    'Broccoli Salad': 'Brokkolisalat',
    'Broccoli Soup': 'Brokkolisuppe',
    'Brown Sauce': 'Brun saus',
    'Buckwheat Burger': 'Bokhveteburger',
    'Bulgur Salad': 'Bulgursalat',
    'Burger Buns': 'Hamburgerbrød',
    'Burger Dressing': 'Burgerdressing',
    'Cabbage Soup': 'Kålsuppe',
    'Caesar Salad': 'Cæsarsalat',
    'Caraway and Cashew Cheese': 'Karve- og cashewost',
    'Cashew Sour Cream': 'Cashew-rømme',
    'Cashew Vanilla Cream': 'Cashew-vaniljekrem',
    'Cashew Bechamel Sauce': 'Cashew-bechamelsaus',
    'Cashew Cheese Sauce': 'Cashew-ostesaus',
    'Cauliflower Soup': 'Blomkålsuppe',
    'Cheese Sauce for Onion Pie': 'Ostesaus til løkpai',
    'Cheesy Cauliflower Sauce': 'Ostete blomkålsaus',
    'Cheezy Cashew Kale Chips': 'Ostete cashew-grønnkålchips',
    'Chickpea Omelet': 'Kikertomelett',
    'Chickpea Salad': 'Kikertsalat',
    'Chickpea Tofu': 'Kikerttofu',
    'Chinese Cabbage Salad': 'Kinakålsalat',
    'Chinese Soup': 'Kinesisk suppe',
    'Breaded Tofu Sticks': 'Paneret tofu i staver',
    'Candy Rolls': 'Godterirundstykker',
    'Caramelized Nuts': 'Karamelliserte nøtter',
    'Carob Spread': 'Johannesbrødpålegg',
    'Chipotle Sauce': 'Chipotlesaus',
    'Chorizo with Potato Taco': 'Chorizo med potet-taco',
    'Citrus Dressing': 'Sitrusdressing',
    'Classic Greek Salad': 'Klassisk gresk salat',
    'Coconut Macaroon Balls': 'Kokosmakron-kuler',
    'Coconut Mozzarella': 'Kokos-mozzarella',
    'Cranberry Jam': 'Tranebærsyltetøy',
    'Croutons': 'Krutonger',
    'Crunchy Carrot Salad': 'Sprø gulrotsalat',
    'Crunchy Sweet Cabbage Salad': 'Sprø sø kålsalat',
    'Cucumber Dressing': 'Agurkdressing',
    'Cucumber Raita': 'Agurk-raita',
    'Cucumber and Sunflowerseed Dressing': 'Agurk- og solsikkedressing',
    'Dal Stew': 'Dal-gryte',
    'Dried Fruit Jam': 'Tørket frukt-syltetøy',
    'Easy Colombian Salad': 'Enkel colombiansk salat',
    "Ellen's Granola": 'Ellens granola',
    "Erik's Granola": 'Eriks granola',
    'Falafel': 'Falafel',
    'Farewell Sesame Eggplant': 'Sesam-aubergine til avskjed',
    'Feld Salad with Pomegranate': 'Feldsalat med granateple',
    'Fermented Red Cabbage': 'Fermentert rødkål',
    'Fig Spread': 'Fikenpålegg',
    'Fresh Vegetable Bouillon': 'Fersk grønnsaksbuljong',
    'Frittata': 'Frittata',
    'Fruit Crisp': 'Fruktcrumble',
    'Fruit Salad': 'Fruktsalat',
    'Garden Vegetable Soup': 'Hagegrønnsakssuppe',
    'Garlic and Cashew Cheese': 'Hvitløks- og cashewost',
    'Gluten Free Oat Buns': 'Glutenfrie havreboller',
    'Golden Soup': 'Gyllen suppe',
    'Green Beans': 'Grønne bønner',
    'Guacamole': 'Guacamole',
    'Happy Beans Salad': 'Glad bønnesalat',
    'Hasselback Potatoes': 'Hasselbackpoteter',
    'Hazelnut and Sundried Tomato Cheese': 'Hasselnøtt- og soltørket tomatost',
    'Homemade Whole Wheat Bread': 'Hjemmelaget grovt brød',
    'Horseradish Dressing': 'Pepperrotdressing',
    'Hummus': 'Hummus',
    'Isabel´s Dressing': 'Isabels dressing',
    'Isabel\u00b4s Dressing': 'Isabels dressing',
    'Italian Bruschetta': 'Italiensk bruschetta',
    'Kale and Sweet Potato Salad': 'Grønnkål- og søtpotetsalat',
    'Kale Avocado': 'Grønnkål med avokado',
    'Kale Chips': 'Grønnkålchips',
    'Kale Soup': 'Grønnkålsuppe',
    "Katrine´s Pesto Dressing": 'Katrines pestodressing',
    "Katrine\u00b4s Pesto Dressing": 'Katrines pestodressing',
    'Ketchup': 'Ketchup',
    'Kidney Bean Stew': 'Kidneybønnegryte',
    'Lasagna': 'Lasagne',
    'Lemon and Olive Oil Dressing': 'Sitron- og olivenoljedressing',
    'Lentil Lap Stew': 'Lapskaus med linser',
    'Lightly Cooked Broccoli': 'Lettkokt brokkoli',
    "Linda´s Gluten Free Bread": 'Lindas glutenfrie brød',
    "Linda\u00b4s Gluten Free Bread": 'Lindas glutenfrie brød',
    "Luke's Indian Chickpea Sauce": 'Lukes indiske kikertsaus',
    "Maddie's Pesto": 'Maddies pesto',
    "Marika's Tofu Balls": 'Marikas tofuboller',
    "Marika's Summer Salad": 'Marikas sommersalat',
    'Marinated Tofu Sticks': 'Marinerte tofustaver',
    'Mashed Potatoes': 'Potetmos',
    'Mediterranean Soup': 'Middelhavssuppe',
    'Millet Crackers, Hirseknekk': 'Hirseknekkebrød',
    'Minestrone Soup': 'Minestronesuppe',
    'Mint Yogurt Dressing': 'Mynte-yoghurtdressing',
    'Noodle Wok': 'Nudelwok',
    'Nordic Sprout Salad': 'Nordisk spiresalat',
    'Nutloaf': 'Nøttestek',
    'Oat Burger': 'Havreburger',
    'Onion Pie Crust': 'Løkpaibunn',
    'Onion Pie Filling': 'Løkpai-fyll',
    'Parmesan': 'Parmesan',
    'Peanut Ginger Dressing': 'Peanøtt- og ingefærdressing',
    'Pickled Ginger': 'Syltet ingefær',
    'Pineapple Cream': 'Ananaskrem',
    'Pizza Crust Dough': 'Pizzabunn-deig',
    'Plant Based Butter': 'Plantebasert smør',
    'Poke Dressing': 'Pokedressing',
    'Poke Tofu': 'Poketofu',
    'Polenta': 'Polenta',
    'Pomodoro Sauce': 'Pomodorosaus',
    'Potato and Spinach Soup': 'Potet- og spinatsuppe',
    'Potato Gratin': 'Potetgrateng',
    'Potato Salad': 'Potetsalat',
    'Protein Shake': 'Proteinshake',
    'Pumpkin Soup': 'Gresskarsuppe',
    'Pumpkinseed and Basil Cheese': 'Gresskarfrø- og basilikumost',
    'Quinoa Salad First': 'Quinoasalat (variant 1)',
    'Quinoa Salad Second': 'Quinoasalat (variant 2)',
    'Ranch Dressing': 'Ranchdressing',
    'Raspberry Jam': 'Bringebærsyltetøy',
    'Raw Cheesecake': 'Rå ostekake',
    'Red Beet Spread': 'Rødbetpålegg',
    'Red Cabbage Salad': 'Rødkålsalat',
    'Red Beet Salad': 'Rødbetsalat',
    'Red Beet Burger': 'Rødbetburger',
    'Red Lentil Soup': 'Rød linsesuppe',
    'Rice Porridge': 'Risgrøt',
    'Roasted Cauliflower': 'Ovnsbakt blomkål',
    'Roasted Pepper Seitan Sausages': 'Ovnsbakt paprika-seitanpølser',
    'Roasted Sweet Potato and Arugula Salad': 'Ovnsbakt søtpotet- og ruccolasalat',
    'Roasted Brussels Sprouts': 'Ovnsbakt rosenkål',
    'Roasted Chickpea Tofu': 'Ovnsbakt kikerttofu',
    'Roasted Salad': 'Ovnsbakt salat',
    'Roti': 'Roti',
    'Russian Penicillin': 'Russisk penicillin',
    'Salsa': 'Salsa',
    'Sautéed Carrots': 'Surret gulrot',
    'Saut\u00e9ed Carrots': 'Surret gulrot',
    'Scrambled Tofu': 'Tofu-eggerøre',
    'Seasoned Baked Potatoes': 'Krydret ovnsbakte poteter',
    'Simple Baked Potatoes': 'Enkle ovnsbakte poteter',
    'Sorbet': 'Sorbet',
    'Soy Mayonnaise': 'Soyamajones',
    'Soy Mozzarella': 'Soya-mozzarella',
    'Soy Salami': 'Soyasalami',
    'Soy Yogurt Dressing': 'Soyayoghurt-dressing',
    'Standard Recipes': 'Standardoppskrifter',
    'Steamed Small Potatoes': 'Dampede små poteter',
    "Stine Gro´s Waffles": 'Stine Gros vafler',
    "Stine Gro\u00b4s Waffles": 'Stine Gros vafler',
    'Strawberry Jam': 'Jordbærsyltetøy',
    'Stuffed Paprika with Tofu': 'Fylt paprika med tofu',
    'Super Green Smoothie': 'Supergrønn smoothie',
    'Swedish Oven Pancake': 'Svensk ovnspannekake',
    'Sweet Potato Muffins': 'Søtpotetmuffins',
    'Sweet Potato Soup': 'Søtpotetsuppe',
    'Sweet Vinaigrette': 'Søt vinaigrette',
    'Sweet Yellow Pea Soup': 'Søt gul ertesuppe',
    'Taco Dressing': 'Tacodressing',
    'Thai Soup': 'Thai-suppe',
    'Tofu Feta Cheese': 'Tofu fetaost',
    'Tofu Sour Cream': 'Tofu-rømme',
    'Tofu Cottage Cheese': 'Tofu cottage cheese',
    'Tofu Form': 'Tofu-form',
    "Tom's Gluten Free Bread": 'Toms glutenfrie brød',
    'Tomato Bruschetta': 'Tomatbruschetta',
    'Tomato Sauce for Pizza': 'Tomatsaus til pizza',
    'Tomato Soup': 'Tomatsuppe',
    'Tomato Bean Salad': 'Tomat- og bønnesalat',
    'Turmeric and Cashew Cheese': 'Gurkemeie- og cashewost',
    'Ukrainian Borscht Soup': 'Ukrainsk borsjtsjsuppe',
    'Vanilla Sauce': 'Vaniljesaus',
    'Vegetable Pie': 'Grønnsakspai',
    'Walnut Basil Dressing': 'Valnøtt- og basilikumdressing',
    'Walnut Milk with Dates': 'Valnøttmelk med dadler',
    'Whipped Cream': 'Pisket krem',
    'White Cabbage Coleslaw': 'Hvitkål-coleslaw',
    'White Cashew Sauce': 'Hvit cashewsaus',
    'Whole Grain Rice': 'Fullkornsris',
    'Salad': 'Salat',
    'Fluffy Vegan Gluten-Free Buns': 'Luftige veganske glutenfrie rundstykker',
    'Fredheim Deluxe Plant-Based Cream Cheese': 'Fredheim deluxe plantebasert kremost',
    'Creamy Red Lentil Stew': 'Kremet rød linsegryte',
    'Ultimate Fluffy Vegan Gluten-Free Bread': 'Ultimativt luftig vegansk glutenfritt brød',
}

# --------------------------------------------------------------------------
# Ingredient names — all unique names hand-translated
# --------------------------------------------------------------------------
INGREDIENTS = {
    # Proteins / nuts / seeds
    'Almonds': 'Mandler',
    'Cashew, unsalted': 'Cashewnøtter, usaltet',
    'Cashew milk': 'Cashewmelk',
    'Cashew sour cream': 'Cashewrømme',
    'Hazelnuts': 'Hasselnøtter',
    'Peanuts': 'Peanøtter',
    'Peanut butter': 'Peanøttsmør',
    'Pecans': 'Pekannøtter',
    'Walnuts': 'Valnøtter',
    'Chia seeds, dried': 'Chiafrø, tørkede',
    'Flaxseed, crushed': 'Linfrø, knust',
    'Flaxseeds': 'Linfrø',
    'Fibre husk': 'Fiberskall',
    'Fenugreek seeds': 'Bukkehornfrø',
    'Sesame seeds, with shell': 'Sesamfrø, med skall',
    'Sesame seeds, without shell': 'Sesamfrø, uten skall',
    'Squash seeds, pumpkin seeds': 'Gresskarfrø',
    'Sunflower seeds': 'Solsikkefrø',
    'Mustard seeds': 'Sennepsfrø',
    'Coriander seeds': 'Korianderfrø',
    'Psyllium husk powder': 'Loppefrøskall, pulver',

    # Legumes / beans
    'Black beans': 'Svarte bønner',
    'Chickpeas, cooked': 'Kikerter, kokte',
    'Chickpeas, dry': 'Kikerter, tørre',
    'Chickpea flour': 'Kikertmel',
    'Kidney beans, red, canned': 'Kidneybønner, røde, hermetiske',
    'Edamame beans, soybeans, frozen': 'Edamamebønner, frosne',
    'Bean noodles, dry': 'Bønnenudler, tørre',
    'White beans, dry': 'Hvite bønner, tørre',
    'White beans, large, canned': 'Hvite bønner, store, hermetiske',
    'Lentils, green and brown, dry': 'Linser, grønne og brune, tørre',
    'Lentils, red/pink, dry': 'Linser, røde/rosa, tørre',
    'Red lentils, rinsed': 'Røde linser, skylt',
    'Yellow peas, cooked': 'Gule erter, kokte',
    'Asparagus beans, frozen': 'Aspargesbønner, frosne',
    'Bean sprouts, mung bean sprouts, raw': 'Bønnespirer, mungbønnespirer, rå',

    # Vegetables
    'Apple cider vinegar': 'Eplecidereddik',
    'Apple, Granny Smith, Golden Delicious, raw': 'Eple, Granny Smith / Golden Delicious, rått',
    'Apple, imported, raw': 'Eple, importert, rått',
    'Apple, Norwegian, unspecified, raw': 'Eple, norsk, uspesifisert, rått',
    'Apple, Red aroma, raw': 'Eple, Red Aroma, rått',
    'Apple, unspecified, raw': 'Eple, uspesifisert, rått',
    'Apricot, raw': 'Aprikos, rå',
    'Arugula': 'Ruccola',
    'Avocado, raw': 'Avokado, rå',
    'Baking potatoes': 'Bakepoteter',
    'Baking powder': 'Bakepulver',
    'Baking soda': 'Natron',
    'Banana, raw': 'Banan, rå',
    'Barley coffee': 'Byggkaffe',
    'Basil, dried': 'Basilikum, tørket',
    'Basil, raw': 'Basilikum, fersk',
    'Bay leaf, dried': 'Laurbærblad, tørket',
    'Beetroot, Norwegian, raw': 'Rødbete, norsk, rå',
    'Bell pepper, green, raw': 'Paprika, grønn, rå',
    'Bell pepper, red, cooked': 'Paprika, rød, kokt',
    'Bell pepper, red, raw': 'Paprika, rød, rå',
    'Bell pepper, yellow/orange, raw': 'Paprika, gul/oransje, rå',
    'Blackberries, raw': 'Bjørnebær, rå',
    'Blueberries, raw': 'Blåbær, rå',
    'Bread crumbs': 'Brødsmuler',
    'Bread crumbs, gluten free': 'Brødsmuler, glutenfrie',
    'Bread, extra coarse (75-100%), purchased, Wholemeal bread without whole grains': 'Brød, ekstra grovt (75–100 %), kjøpt, grovbrød uten hele korn',
    'Bread, extra coarse, 75% wholemeal, home-baked': 'Brød, ekstra grovt, 75 % grovt, hjemmebakt',
    'Broccoli, Norwegian, raw': 'Brokkoli, norsk, rå',
    'Broccoli, unspecified, raw': 'Brokkoli, uspesifisert, rå',
    'Brussels sprouts, frozen': 'Rosenkål, frossen',
    'Buckwheat flour': 'Bokhvete-mel',
    'Buckwheat, whole grain': 'Bokhvete, hel',
    'Bulgur groats, dry': 'Bulgurgryn, tørre',
    'Canola oil': 'Rapsolje',
    'Caraway, cumin, whole': 'Karve, hel',
    'Carob powder': 'Johannesbrødpulver',
    'Carrot, cooked': 'Gulrot, kokt',
    'Carrot, imported, raw': 'Gulrot, importert, rå',
    'Carrot, Norwegian, raw': 'Gulrot, norsk, rå',
    'Carrot, unspecified, raw': 'Gulrot, uspesifisert, rå',
    'Cauliflower, Norwegian, raw': 'Blomkål, norsk, rå',
    'Celery root, Norwegian, raw': 'Sellerirot, norsk, rå',
    'Celery stalks, Norwegian, raw': 'Stangselleri, norsk, rå',
    'Cherry tomato, imported, raw': 'Cherrytomat, importert, rå',
    'Chili powder': 'Chilipulver',
    'Chili, red, raw': 'Chili, rød, rå',
    'Chilli flakes': 'Chiliflak',
    'Chinese cabbage, Norwegian, raw': 'Kinakål, norsk, rå',
    'Chives, raw': 'Gressløk, fersk',
    'Cinnamon': 'Kanel',
    'Cinnamon, ground': 'Kanel, malt',
    'Cloves, ground': 'Nellik, malt',
    'Coconut milk': 'Kokosmelk',
    'Coconut oil': 'Kokosolje',
    'Coconut, shredded': 'Kokos, revet',
    'Cold water': 'Kaldt vann',
    'Coriander powder': 'Korianderpulver',
    'Coriander, dried': 'Koriander, tørket',
    'Coriander, raw': 'Koriander, fersk',
    'Corn flour, polenta': 'Maismel, polenta',
    'Corn, frozen': 'Mais, frossen',
    'Cornstarch': 'Maisstivelse',
    'Cranberries dried': 'Tranebær, tørkede',
    'Crushed tomatoes': 'Knuste tomater',
    'Cucumber, Norwegian, raw': 'Agurk, norsk, rå',
    'Cumin powder': 'Spisskummen, malt',
    'Curry, ground': 'Karri, malt',
    'Date paste': 'Daddelpuré',
    'Date, dried': 'Dadler, tørkede',
    'Dill, dry': 'Dill, tørket',
    'Dill, raw': 'Dill, fersk',
    'Eggplant, raw': 'Aubergine, rå',
    'Feld salad': 'Feldsalat',
    'Fennel, raw': 'Fennikel, rå',
    'Figs, dried': 'Fikener, tørkede',
    'Flour, gluten-free, Jyttemel Original': 'Mel, glutenfritt, Jyttemel Original',
    'Fresh chives, chopped': 'Fersk gressløk, hakket',
    'Fresh cilantro, chopped': 'Fersk koriander, hakket',
    'Fresh dill, chopped': 'Fersk dill, hakket',
    'Fresh lemon juice': 'Fersk sitronsaft',
    'Garam Masala': 'Garam masala',
    'Garlic cloves, minced': 'Hvitløksfedd, finhakkede',
    'Garlic powder': 'Hvitløkspulver',
    'Garlic, raw': 'Hvitløk, rå',
    'Ginger, powder': 'Ingefær, pulver',
    'Ginger, raw': 'Ingefær, fersk',
    'Gluten flour': 'Glutenmel',
    'Gluten-free bread flour': 'Glutenfritt brødmel',
    'Gluten-free oat flour': 'Glutenfritt havremel',
    'Grape, blue, raw': 'Druer, blå, rå',
    'Grape, unspecified, raw': 'Druer, uspesifisert, rå',
    'Ground coriander': 'Koriander, malt',
    'Ground cumin': 'Spisskummen, malt',
    'Head cabbage, raw': 'Hodekål, rå',
    'Herb salt': 'Urtesalt',
    'Honey': 'Honning',
    'Honeydew melon, raw': 'Honningmelon, rå',
    'Horseradish, raw': 'Pepperrot, fersk',
    'Hot sauce': 'Sterk saus',
    'Instant dry yeast': 'Hurtiggjær',
    'Instant yeast': 'Hurtiggjær',
    'Kale, raw': 'Grønnkål, rå',
    'Ketchup, tomato ketchup': 'Ketchup',
    'Large carrot, diced': 'Stor gulrot, i terninger',
    'Lasagne sheets': 'Lasagneplater',
    'Leeks, Norwegian, raw': 'Purre, norsk, rå',
    'Lemon juice': 'Sitronsaft',
    'Lemon juice, bottled': 'Sitronsaft, på flaske',
    'Lemon juice, fresh': 'Sitronsaft, fersk',
    'Lemon peel': 'Sitronskall',
    'Lemon zest': 'Sitronskall',
    'Lemon, juice': 'Sitronsaft',
    'Lemon, raw': 'Sitron, fersk',
    'Lemon': 'Sitron',
    'Lime juice': 'Limesaft',
    'Lingoberries, raw': 'Tyttebær, rå',
    'Maple syrup': 'Lønnesirup',
    'Marjoram, dried': 'Merian, tørket',
    'Medium onion, finely chopped': 'Middels løk, finhakket',
    'Medjool dates, pitted': 'Medjool-dadler, uten stein',
    'Millet, whole grai': 'Hirse, hel',
    'Millet, whole grain': 'Hirse, hel',
    'Mint, fresh': 'Mynte, fersk',
    'Miso, fermented soy bean paste': 'Miso (fermentert soyabønnepasta)',
    'Neutral oil': 'Nøytral olje',
    'Non-diary milk': 'Plantemelk',
    'Nori, dried seaweed': 'Nori, tørket tang',
    'Nutmeg, ground': 'Muskatnøtt, malt',
    'Nutritional yeast': 'Næringsgjær',
    'Oat flakes, Oat flakes': 'Havregryn',
    'Oat flour': 'Havremel',
    'Oat milk': 'Havremelk',
    'Oats, big': 'Havregryn, store',
    'Olive oil': 'Olivenolje',
    'Olive oil, extra virgin, virgin oil': 'Olivenolje, ekstra virgin',
    'Olive water': 'Olivenvann (saltlake)',
    'Olive, black, canned': 'Oliven, sorte, hermetiske',
    'Olives, greens, pickles': 'Grønne oliven, sylteagurk',
    'Onion powder': 'Løkpulver',
    'Onion, red, Norwegian, raw': 'Løk, rød, norsk, rå',
    'Onion, yellow, Norwegian, raw': 'Løk, gul, norsk, rå',
    'Orange juice': 'Appelsinjuice',
    'Orange, raw': 'Appelsin, rå',
    'Oregano, dried': 'Oregano, tørket',
    'Paprika powder': 'Paprikapulver',
    'Parsley, dried': 'Persille, tørket',
    'Parsley, Norwegian, raw': 'Persille, norsk, fersk',
    'Parsnip, raw': 'Pastinakk, rå',
    'Pasta, whole grain, dry': 'Pasta, fullkorn, tørr',
    'Pear, imported, raw': 'Pære, importert, rå',
    'Pepper, black': 'Pepper, sort',
    'Pepper, cayenne, red': 'Kajennepepper',
    'Pepper, white': 'Pepper, hvit',
    'Pineapple juice': 'Ananasjuice',
    'Pineapple, canned, with its own juice': 'Ananas, hermetisk, i egen kraft',
    'Plum, raw': 'Plomme, rå',
    'Pomegranate, raw': 'Granateple, rått',
    'Potato flour': 'Potetmel',
    'Potato, raw': 'Potet, rå',
    'Prunes': 'Svisker',
    'Pumpkin, raw': 'Gresskar, rått',
    'Quinoa, white, dry': 'Quinoa, hvit, tørr',
    'Radish, Norwegian, raw': 'Reddik, norsk, rå',
    'Raisins': 'Rosiner',
    'Rapeseed oil': 'Rapsolje',
    'Raspberries, raw': 'Bringebær, rå',
    'Raw cashews for milk': 'Rå cashewnøtter til melk',
    'Raw cashews, soaked': 'Rå cashewnøtter, bløtlagte',
    'Red beet, raw': 'Rødbete, rå',
    'Red bell pepper, diced': 'Rød paprika, i terninger',
    'Red cabbage, raw': 'Rødkål, rå',
    'Rice flour': 'Rismel',
    'Rice noodles, dry': 'Risnudler, tørre',
    'Romaine lettuce, raw': 'Romanosalat, rå',
    'Rosemary, dried': 'Rosmarin, tørket',
    'Rosemary, raw': 'Rosmarin, fersk',
    'Ruccola lettuce, raw': 'Ruccola, rå',
    'Sage, dry': 'Salvie, tørket',
    'Salt': 'Salt',
    'Salt, table salt': 'Salt, bordsalt',
    'Sea salt': 'Havsalt',
    'Sesame oil': 'Sesamolje',
    'Small oats': 'Små havregryn',
    'Small potatoes, diced': 'Små poteter, i terninger',
    'Smoked paprika': 'Røkt paprikapulver',
    'Smoked paprika powder': 'Røkt paprikapulver',
    'Snow peas': 'Snøerter',
    'Soy mayonnaise': 'Soyamajones',
    'Soy milk': 'Soyamelk',
    'Soy sauce': 'Soyasaus',
    'Soy yogurt': 'Soyayoghurt',
    'Spelt flour': 'Speltmel',
    'Spinach, frozen, raw': 'Spinat, frossen',
    'Spinach, raw': 'Spinat, fersk',
    'Spring onions, raw': 'Vårløk, fersk',
    'Squash, zucchini, raw': 'Squash, zucchini, rå',
    'Strawberries, raw': 'Jordbær, rå',
    'Sugar': 'Sukker',
    'Sukrin': 'Sukrin',
    'Sweet potato, raw': 'Søtpotet, rå',
    'Tahini': 'Tahini',
    'Tandoori Masala': 'Tandoori masala',
    'Tapioca starch': 'Tapiokastivelse',
    'Tarragon, dried': 'Estragon, tørket',
    'Thyme, dried': 'Timian, tørket',
    'Thyme, raw': 'Timian, fersk',
    'Tofu, soyabønneprodukt': 'Tofu (soyabønneprodukt)',
    'Tofu, soyab\u00f8nneprodukt': 'Tofu (soyabønneprodukt)',
    'Tofu, soyabnneprodukt': 'Tofu (soyabønneprodukt)',
    'Tomato Bruschette': 'Tomatbruschetta',
    'Tomato puree': 'Tomatpuré',
    'Tomato puree, canned': 'Tomatpuré, hermetisk',
    'Tomato, canned': 'Tomat, hermetisk',
    'Tomato, chopped, tetrapak': 'Tomat, hakket, tetrapakk',
    'Tomato, imported, raw': 'Tomat, importert, rå',
    'Tomato, Norwegian, raw': 'Tomat, norsk, rå',
    'Tomato, unspecified, raw': 'Tomat, uspesifisert, rå',
    'Tomatoes, sun-dried, dry': 'Tomater, soltørkede, tørre',
    'Turmeric': 'Gurkemeie',
    'Turmeric, ground': 'Gurkemeie, malt',
    'Unsweetened applesauce': 'Eplemos, usøtet',
    'Vanilla powder': 'Vaniljepulver',
    'Vegan mozzarella': 'Vegansk mozzarella',
    'Vegetable bouillon, fresh': 'Grønnsaksbuljong, fersk',
    'Vegetable bouillon, powder': 'Grønnsaksbuljong, pulver',
    'Vegetable broth': 'Grønnsaksbuljong',
    'Warm water': 'Lunkent vann',
    'Water': 'Vann',
    'water': 'Vann',
    'Water for milk': 'Vann til melk',
    'Water for tangzhong': 'Vann til tangzhong',
    'Water, drinking water': 'Vann, drikkevann',
    'Watermelon, raw': 'Vannmelon, rå',
    'White cashew sauce': 'Hvit cashewsaus',
    'White flour, fine': 'Hvetemel, fint',
    'White miso': 'Hvit miso',
    'Whole grain rice': 'Fullkornsris',
    'Whole wheat flour, course': 'Sammalt hvetemel, grovt',
    'Whole wheat flour, fine': 'Sammalt hvetemel, fint',
    'Yeast, dry yeast': 'Gjær, tørrgjær',
    'Agar-agar': 'Agar-agar',
    'Black salt': 'Svart salt (kala namak)',
    'M': 'M',
    'Tomato Bruschette': 'Tomatbruschetta',

    # The weird prep-descriptor "ingredient" names from the malformed avocado-dressing
    # recipe — translate as prep descriptors so they at least render sensibly
    'kokt': 'kokt',
    'i små terninger': 'i små terninger',
    'i terninger': 'i terninger',
    'i grove terninger': 'i grove terninger',
    'i tynne skiver': 'i tynne skiver',
    'i skiver': 'i skiver',
    'i tykke skiver': 'i tykke skiver',
    'finhakket': 'finhakket',
    'varm': 'varm',
    'kald': 'kald',
    'kokende': 'kokende',
    'siktet': 'siktet',
    'silt': 'silt',
    'most': 'most',
    'skrellet': 'skrellet',
    'hakket': 'hakket',
    'grovhakket': 'grovhakket',
    'blanchert': 'blanchert',
    'smeltet': 'smeltet',
    'fast': 'fast',
    'finmalt': 'finmalt',
    'revet': 'revet',
    'revet, smått': 'revet, smått',
    'revet, stort': 'revet, stort',
    'ristet': 'ristet',
    'strimlet': 'strimlet',
    'smuldret': 'smuldret',
    'lunkent': 'lunkent',
    'uten stilk': 'uten stilk',
    'blader': 'blader',
    'moden': 'moden',
    'juiced': 'juicet',
    'bløtlagt': 'bløtlagt',
    'brunoise': 'brunoise',
    'halvert': 'halvert',
    'frossen': 'frossen',
    'valgfri': 'valgfri',
    'stilken': 'stilken',
    'kvart': 'kvart',
    'fin': 'fin',
    'uten stein': 'uten stein',
    'uskrellet': 'uskrellet',
    'plante': 'plante',
    'revet/strimlede': 'revet/strimlede',
    'små buketter': 'små buketter',
    'knust': 'knust',
}

# --------------------------------------------------------------------------
# Units
# --------------------------------------------------------------------------
UNIT_MAP = {
    'tbsp': 'ss',
    'tsp': 'ts',
    'pcs': 'stk',
    'clove': 'fedd',
    'cup': 'kopp',
    'pinch': 'klype',
    'handful': 'håndfull',
    'envelope': 'pose',
    'small': 'liten',
    'medium': 'middels',
    'large': 'stor',
    'g': 'g',
    'kg': 'kg',
    'dl': 'dl',
    'ml': 'ml',
    'l': 'l',
    'oz': 'oz',
    'fl_oz': 'fl oz',
}

# --------------------------------------------------------------------------
# Step translation — phrase-level dictionary for common recipe sentences,
# plus a word-substitution fallback.
# --------------------------------------------------------------------------
STEP_PHRASES = [
    # Full-sentence patterns (case-insensitive, regex)
    # Order matters — put most specific first
    (r'^Blend all (the )?ingredients together until smooth\.?$',
     'Kjør alle ingrediensene sammen til en jevn masse.'),
    (r'^Blend all ingredients in a (?:high[- ]speed )?blender until smooth\.?$',
     'Kjør alle ingrediensene i en blender til en jevn masse.'),
    (r'^Mix all the ingredients together\.?$',
     'Bland alle ingrediensene.'),
    (r'^Mix it together\.?$', 'Bland det sammen.'),
    (r'^Serve hot\.?$', 'Serveres varm.'),
    (r'^Serve (it )?cold\.?$', 'Serveres kald.'),
    (r'^Serve cold or at? room temperature\.?$', 'Serveres kald eller tempererert.'),
    (r'^Put in a dressing bottle\.?$', 'Hell over i en dressingflaske.'),
    (r'^Preheat the oven to (\d+)\s*°?C\.?$', r'Forvarm ovnen til \1 °C.'),
    (r'^Preheat the oven to (\d+)\s*(?:celsius|degrees? celsius)\.?$', r'Forvarm ovnen til \1 °C.'),
]

# Word-level substitutions for free-form step text. Applied AFTER phrase
# matching, case-insensitively as whole-word substitutions.
STEP_WORDS = {
    # Cooking verbs
    'preheat the oven to': 'forvarm ovnen til',
    'preheat the oven': 'forvarm ovnen',
    'bring to a boil': 'kok opp',
    'bring to boil': 'kok opp',
    'bring it to boil': 'kok det opp',
    'bring it to a boil': 'kok det opp',
    'bring to a simmer': 'la det småputre',
    'let simmer': 'la småputre',
    'simmer for': 'la småputre i',
    'let it boil': 'la det koke',
    'let it cool': 'la det avkjøles',
    'let cool': 'avkjøl',
    'cool down': 'avkjøl',
    'boil for': 'kok i',
    'cook for': 'kok i',
    'bake for': 'stek i',
    'baking for': 'steking i',
    'bake in a preheated oven': 'stek i forvarmet ovn',
    'bake on': 'stek på',
    'bake at': 'stek på',
    'bake in the oven': 'stek i ovnen',
    'roast for': 'stek i',
    'roast in the oven': 'stek i ovnen',
    'in the oven at': 'i ovnen på',
    'in the oven for': 'i ovnen i',
    'stir well': 'rør godt',
    'stir frequently': 'rør ofte',
    'stir often': 'rør ofte',
    'stir occasionally': 'rør av og til',
    'stir continuously': 'rør kontinuerlig',
    'stir continually': 'rør kontinuerlig',
    'stir until smooth': 'rør til en jevn masse',
    'whisk together': 'visp sammen',
    'whisk the': 'visp',
    'mix together': 'bland sammen',
    'mix well': 'bland godt',
    'mix in': 'bland inn',
    'mix the': 'bland',
    'add the': 'tilsett',
    'add in': 'tilsett',
    'add a pinch': 'tilsett en klype',
    'add salt to taste': 'smak til med salt',
    'add water': 'tilsett vann',
    'add oil': 'tilsett olje',
    'add to the pot': 'ha i kjelen',
    'pour into': 'hell i',
    'pour over': 'hell over',
    'cover with': 'dekk med',
    'cover the': 'dekk',
    'cover and': 'dekk til og',
    'place them': 'legg dem',
    'place it': 'legg det',
    'place the': 'legg',
    'place in': 'legg i',
    'place on': 'legg på',
    'cut into': 'skjær i',
    'cut the': 'skjær',
    'cut them': 'skjær dem',
    'chop the': 'hakk',
    'chop it': 'hakk det',
    'chop finely': 'finhakk',
    'finely chop': 'finhakk',
    'finely chopped': 'finhakket',
    'roughly chop': 'grovhakk',
    'roughly chopped': 'grovhakket',
    'peel and': 'skrell og',
    'peel the': 'skrell',
    'slice the': 'skjær i skiver',
    'thinly sliced': 'i tynne skiver',
    'thickly sliced': 'i tykke skiver',
    'dice the': 'skjær i terninger',
    'diced': 'i terninger',
    'mince the': 'finhakk',
    'minced': 'finhakket',
    'grate the': 'riv',
    'grated': 'revet',
    'drain the': 'la vannet renne av',
    'drain and': 'la renne av og',
    'rinse with': 'skyll med',
    'rinse the': 'skyll',
    'set aside': 'sett til side',
    'let it rise': 'la den heve',
    'let it raise': 'la den heve',
    'let them rise': 'la dem heve',
    'let the dough rise': 'la deigen heve',
    'knead the dough': 'elt deigen',
    'knead for': 'elt i',
    'shape the dough': 'form deigen',
    'shape them into': 'form dem til',
    'divide the dough': 'del deigen',
    'transfer to a': 'overfør til en',
    'transfer into a': 'overfør til en',
    'place on a baking sheet': 'legg på et stekebrett',
    'place on baking tray': 'legg på et stekebrett',
    'baking sheet': 'stekebrett',
    'baking tray': 'stekebrett',
    'baking paper': 'bakepapir',
    'bakingpaper': 'bakepapir',
    'parchment paper': 'bakepapir',
    'food processor': 'foodprosessor',
    'food prosessor': 'foodprosessor',
    'high-speed blender': 'kraftig blender',
    'high speed blender': 'kraftig blender',
    'hand blender': 'stavmikser',
    'heat the oil': 'varm oljen',
    'heat oil': 'varm olje',
    'heat a': 'varm en',
    'medium heat': 'middels varme',
    'low heat': 'lav varme',
    'high heat': 'høy varme',
    'over medium heat': 'på middels varme',
    'over low heat': 'på lav varme',
    'over high heat': 'på høy varme',
    'until golden brown': 'til de er gyllenbrune',
    'until golden': 'til de er gylne',
    'until soft': 'til de er myke',
    'until tender': 'til de er møre',
    'until smooth': 'til en jevn masse',
    'until cooked through': 'til det er gjennomkokt',
    'until warmed through': 'til det er gjennomvarmt',
    'until softened': 'til de er myke',
    'until translucent': 'til de er blanke',
    'until translusent': 'til de er blanke',
    'until bright green': 'til de er knallgrønne',
    'until the onion is': 'til løken er',
    'until the onions are': 'til løkene er',
    'until well combined': 'til alt er godt blandet',
    'until combined': 'til alt er blandet',
    'until evenly mixed': 'til alt er jevnt blandet',
    'until fully done': 'til de er ferdige',
    'until foamy': 'til den er skummende',
    'for another': 'i ytterligere',
    'for about': 'i ca.',
    'for approximately': 'i ca.',
    'approximately': 'ca.',
    'minutes': 'minutter',
    'minute': 'minutt',
    'seconds': 'sekunder',
    'hours': 'timer',
    'hour': 'time',
    'overnight': 'over natten',
    'on the side': 'ved siden av',
    'from the heat': 'fra varmen',
    'off the heat': 'av varmen',
    'remove from the heat': 'ta av varmen',
    'take off the heat': 'ta av varmen',
    'in a bowl': 'i en bolle',
    'in a large bowl': 'i en stor bolle',
    'in a small bowl': 'i en liten bolle',
    'in a pot': 'i en kjele',
    'in a large pot': 'i en stor kjele',
    'in a pan': 'i en panne',
    'in a large pan': 'i en stor panne',
    'in a skillet': 'i en stekepanne',
    'in a frying pan': 'i en stekepanne',
    'in a blender': 'i en blender',
    'in a jar': 'i et glass',
    'in a saucepan': 'i en kasserolle',
    'taste for seasoning': 'smak til med krydder',
    'taste and adjust': 'smak til og juster',
    'season with': 'krydre med',
    'season the': 'krydre',
    'salt and pepper': 'salt og pepper',
    'salt to taste': 'salt etter smak',
    'to taste': 'etter smak',
    'as needed': 'etter behov',
    'if needed': 'om nødvendig',
    'if desired': 'om ønskelig',
    'if you like': 'hvis du ønsker',
    'if you prefer': 'hvis du foretrekker',
    'top with': 'topp med',
    'garnish with': 'garner med',
    'sprinkle with': 'dryss over',
    'sprinkle some': 'dryss litt',
    'sprinkle on': 'dryss på',
    'before serving': 'før servering',
    'just before serving': 'rett før servering',
    'keep warm': 'hold varm',
    'store in the refrigerator': 'oppbevar i kjøleskap',
    'store in a': 'oppbevar i en',
    'refrigerate': 'sett i kjøleskap',
    'refrigerator': 'kjøleskap',
    'freeze': 'frys',
    'defrost': 'tin',
    'thaw': 'tin',
    'ripe': 'moden',
    'ripened': 'modnet',
    'peeled': 'skrelt',
    'chopped': 'hakket',
    'sliced': 'i skiver',
    'melted': 'smeltet',
    'softened': 'mykt',
    'cooled': 'avkjølt',
    'cooled down': 'avkjølt',
    'warm': 'varm',
    'cold': 'kald',
    'hot': 'varm',
    # Ingredients in steps
    'olive oil': 'olivenolje',
    'coconut oil': 'kokosolje',
    'sesame oil': 'sesamolje',
    'canola oil': 'rapsolje',
    'oil': 'olje',
    'salt': 'salt',
    'sea salt': 'havsalt',
    'pepper': 'pepper',
    'cayenne pepper': 'kajennepepper',
    'black pepper': 'sort pepper',
    'water': 'vann',
    'warm water': 'lunkent vann',
    'cold water': 'kaldt vann',
    'boiling water': 'kokende vann',
    'almond milk': 'mandelmelk',
    'soy milk': 'soyamelk',
    'oat milk': 'havremelk',
    'coconut milk': 'kokosmelk',
    'onion': 'løk',
    'onions': 'løk',
    'garlic': 'hvitløk',
    'lemon juice': 'sitronsaft',
    'lemon': 'sitron',
    'lime': 'lime',
    'avocado': 'avokado',
    'tomato': 'tomat',
    'tomatoes': 'tomater',
    'carrots': 'gulrøtter',
    'carrot': 'gulrot',
    'potato': 'potet',
    'potatoes': 'poteter',
    'sweet potato': 'søtpotet',
    'sweet potatoes': 'søtpoteter',
    'broccoli': 'brokkoli',
    'cauliflower': 'blomkål',
    'cabbage': 'kål',
    'red cabbage': 'rødkål',
    'chinese cabbage': 'kinakål',
    'kale': 'grønnkål',
    'spinach': 'spinat',
    'eggplant': 'aubergine',
    'aubergine': 'aubergine',
    'leek': 'purre',
    'leeks': 'purre',
    'bell pepper': 'paprika',
    'red bell pepper': 'rød paprika',
    'mushroom': 'sopp',
    'mushrooms': 'sopp',
    'cucumber': 'agurk',
    'parsley': 'persille',
    'coriander': 'koriander',
    'cilantro': 'koriander',
    'thyme': 'timian',
    'rosemary': 'rosmarin',
    'basil': 'basilikum',
    'oregano': 'oregano',
    'dill': 'dill',
    'mint': 'mynte',
    'ginger': 'ingefær',
    'chili': 'chili',
    'chilli': 'chili',
    'turmeric': 'gurkemeie',
    'cumin': 'spisskummen',
    'paprika powder': 'paprikapulver',
    'smoked paprika': 'røkt paprikapulver',
    'paprika': 'paprika',
    'cinnamon': 'kanel',
    'nutmeg': 'muskatnøtt',
    'clove': 'fedd',
    'cloves': 'fedd',
    'nutritional yeast': 'næringsgjær',
    'garlic powder': 'hvitløkspulver',
    'onion powder': 'løkpulver',
    'vegetable bouillon': 'grønnsaksbuljong',
    'bouillon': 'buljong',
    'broth': 'buljong',
    'stock': 'kraft',
    'soy sauce': 'soyasaus',
    'tomato paste': 'tomatpuré',
    'tomato puree': 'tomatpuré',
    'tomato sauce': 'tomatsaus',
    'maple syrup': 'lønnesirup',
    'honey': 'honning',
    'sugar': 'sukker',
    'flour': 'mel',
    'cornstarch': 'maisstivelse',
    'corn starch': 'maisstivelse',
    'cashews': 'cashewnøtter',
    'almonds': 'mandler',
    'walnuts': 'valnøtter',
    'peanuts': 'peanøtter',
    'hazelnuts': 'hasselnøtter',
    'seeds': 'frø',
    'chia seeds': 'chiafrø',
    'flaxseeds': 'linfrø',
    'sunflower seeds': 'solsikkefrø',
    'sesame seeds': 'sesamfrø',
    'pumpkin seeds': 'gresskarfrø',
    'rolled oats': 'havregryn',
    'oats': 'havregryn',
    'rice': 'ris',
    'pasta': 'pasta',
    'quinoa': 'quinoa',
    'bulgur': 'bulgur',
    'lentils': 'linser',
    'red lentils': 'røde linser',
    'chickpeas': 'kikerter',
    'beans': 'bønner',
    'black beans': 'svarte bønner',
    'kidney beans': 'kidneybønner',
    'white beans': 'hvite bønner',
    'tofu': 'tofu',
    'yeast': 'gjær',
    'baking powder': 'bakepulver',
    'baking soda': 'natron',
    'vanilla': 'vanilje',
    'berries': 'bær',
    'blueberries': 'blåbær',
    'strawberries': 'jordbær',
    'raspberries': 'bringebær',
    'dates': 'dadler',
    'raisins': 'rosiner',
    # Units in prose
    'teaspoons': 'teskjeer',
    'teaspoon': 'teskje',
    'tablespoons': 'spiseskjeer',
    'tablespoon': 'spiseskje',
    # Connectors
    'and': 'og',
    'or': 'eller',
    'with': 'med',
    'without': 'uten',
    'about': 'ca.',
    'approximately': 'ca.',
    # Prepositions / pronouns (after longer phrases to avoid false hits)
    'then': 'så',
    'after that': 'deretter',
    'meanwhile': 'imens',
    'next': 'deretter',
    'first': 'først',
    'finally': 'til slutt',

    # === Cooking verbs (solo verbs — put AFTER the phrase versions above) ===
    'sauté': 'surr',
    'saute': 'surr',
    'sautéed': 'surret',
    'sauteed': 'surret',
    'sauté the': 'surr',
    'saute the': 'surr',
    'sautéé': 'surr',
    'sweat': 'surr',
    'sweat the': 'surr',
    'sweating': 'surring',
    'fry': 'stek',
    'frying': 'steking',
    'fried': 'stekt',
    'cook': 'kok',
    'cooking': 'koking',
    'cooked': 'kokt',
    'boil': 'kok',
    'boiling': 'kokende',
    'boiled': 'kokt',
    'bake': 'stek',
    'baking': 'steking',
    'baked': 'stekt',
    'roast': 'stek',
    'roasting': 'steking',
    'roasted': 'stekt',
    'blend': 'kjør',
    'blending': 'kjøring',
    'blended': 'kjørt',
    'whisk': 'visp',
    'whisked': 'vispet',
    'stir': 'rør',
    'stirring': 'rør',
    'stirred': 'rørt',
    'mix': 'bland',
    'mixed': 'blandet',
    'mixing': 'blanding',
    'add': 'tilsett',
    'added': 'tilsatt',
    'adding': 'tilsetning',
    'remove': 'fjern',
    'removed': 'fjernet',
    'removing': 'fjerning',
    'have': 'ha',
    'place': 'legg',
    'put': 'ha',
    'pour': 'hell',
    'poured': 'helt',
    'pouring': 'helling',
    'cover': 'dekk',
    'covered': 'dekket',
    'covering': 'dekking',
    'cut': 'skjær',
    'cutting': 'skjæring',
    'chop': 'hakk',
    'chopping': 'hakking',
    'slice': 'skjær i skiver',
    'slicing': 'skjæring',
    'dice': 'skjær i terninger',
    'dicing': 'skjæring i terninger',
    'peel': 'skrell',
    'peeling': 'skrelling',
    'grate': 'riv',
    'grating': 'riving',
    'drain': 'la renne av',
    'drained': 'avdryppet',
    'rinse': 'skyll',
    'rinsed': 'skylt',
    'rinsing': 'skylling',
    'knead': 'elt',
    'kneading': 'elting',
    'kneaded': 'eltet',
    'shape': 'form',
    'shaping': 'forming',
    'shaped': 'formet',
    'divide': 'del',
    'dividing': 'deling',
    'divided': 'delt',
    'transfer': 'overfør',
    'transferring': 'overføring',
    'transferred': 'overført',
    'combine': 'bland',
    'combined': 'blandet',
    'combining': 'blanding',
    'roll': 'rull',
    'rolling': 'rulling',
    'rolled': 'rullet',
    'taste': 'smak',
    'tasting': 'smaking',
    'tasted': 'smakt',
    'season': 'krydre',
    'seasoned': 'krydret',
    'seasoning': 'krydder',
    'serve': 'server',
    'serving': 'servering',
    'served': 'servert',
    'spread': 'spre',
    'spreading': 'spredning',
    'wash': 'vask',
    'washing': 'vasking',
    'washed': 'vasket',
    'dry': 'tørk',
    'drying': 'tørking',
    'dried': 'tørket',
    'mash': 'mos',
    'mashing': 'mosing',
    'mashed': 'most',
    'melt': 'smelt',
    'melting': 'smelting',
    'melted': 'smeltet',
    'soak': 'bløtlegg',
    'soaked': 'bløtlagt',
    'soaking': 'bløtlegging',
    'crush': 'knus',
    'crushed': 'knust',
    'crushing': 'knusing',
    'toss': 'vend',
    'tossing': 'vending',
    'tossed': 'vendt',
    'flip': 'snu',
    'flipping': 'snuing',
    'flipped': 'snudd',
    'turn': 'snu',
    'turning': 'snuing',
    'turned': 'snudd',
    'marinate': 'marinér',
    'marinated': 'marinert',
    'marinating': 'marinering',
    'squeeze': 'klem',
    'squeezed': 'presset',
    'squeezing': 'pressing',
    'toast': 'rist',
    'toasted': 'ristet',
    'toasting': 'risting',
    'simmer': 'la småputre',
    'simmered': 'småputret',
    'simmering': 'småputring',
    'steam': 'damp',
    'steaming': 'damping',
    'steamed': 'dampet',
    'grill': 'grill',
    'grilling': 'grilling',
    'grilled': 'grillet',
    'preheat': 'forvarm',
    'preheated': 'forvarmet',
    'bring': 'bring',
    'brought': 'brakt',
    'heat': 'varm',
    'heated': 'oppvarmet',
    'heating': 'oppvarming',
    'cool': 'avkjøl',
    'cooled': 'avkjølt',
    'cooling': 'avkjøling',
    'let': 'la',
    'let the': 'la',
    'let it': 'la det',
    'let them': 'la dem',
    'use': 'bruk',
    'used': 'brukt',
    'using': 'bruk av',
    'continue': 'fortsett',
    'continued': 'fortsatte',
    'continuing': 'fortsettelse',
    'repeat': 'gjenta',
    'repeated': 'gjentatt',
    'repeating': 'gjentakelse',
    'start': 'start',
    'started': 'startet',
    'starting': 'start',
    'begin': 'begynn',
    'beginning': 'begynnelse',
    'finish': 'avslutt',
    'finished': 'ferdig',
    'finishing': 'avslutning',
    'adjust': 'juster',
    'adjusted': 'justert',
    'adjusting': 'justering',
    'check': 'sjekk',
    'checked': 'sjekket',
    'checking': 'sjekking',
    'process': 'prosesser',
    'processed': 'prosessert',
    'processing': 'prosessering',
    'scrape': 'skrap',
    'scraped': 'skrapet',
    'scraping': 'skraping',
    'sprinkle': 'dryss',
    'sprinkled': 'drysset',
    'sprinkling': 'drysning',

    # === Nouns / cooking terms ===
    'ingredients': 'ingrediensene',
    'ingredient': 'ingrediens',
    'mixture': 'blanding',
    'dough': 'deig',
    'batter': 'røre',
    'sauce': 'saus',
    'soup': 'suppe',
    'stew': 'gryte',
    'salad': 'salat',
    'dressing': 'dressing',
    'pan': 'panne',
    'pot': 'kjele',
    'bowl': 'bolle',
    'tray': 'brett',
    'sheet': 'brett',
    'dish': 'form',
    'paper': 'papir',
    'foil': 'folie',
    'towel': 'håndkle',
    'spoon': 'skje',
    'fork': 'gaffel',
    'knife': 'kniv',
    'lid': 'lokk',
    'stove': 'komfyr',
    'oven': 'ovn',
    'fridge': 'kjøleskap',
    'freezer': 'fryser',
    'heat': 'varme',
    'temperature': 'temperatur',
    'degrees': 'grader',
    'degree': 'grad',
    'celsius': '°C',
    'celsisus': '°C',
    'piece': 'stykke',
    'pieces': 'stykker',
    'small pieces': 'små stykker',
    'large pieces': 'store stykker',
    'even pieces': 'jevne stykker',
    'wedge': 'båt',
    'wedges': 'båter',
    'vedges': 'båter',
    'florets': 'buketter',
    'floret': 'bukett',
    'stem': 'stilk',
    'stems': 'stilker',
    'leaves': 'blader',
    'leaf': 'blad',
    'layer': 'lag',
    'layers': 'lag',
    'single layer': 'ett lag',
    'portion': 'porsjon',
    'portions': 'porsjoner',
    'tip': 'tips',
    'tips': 'tips',
    'option': 'alternativ',
    'options': 'alternativer',
    'side': 'side',
    'sides': 'sider',
    'half': 'halvparten',
    'halves': 'halvdeler',
    'pinch': 'klype',
    'pinches': 'klyper',
    'handful': 'håndfull',
    'dash': 'dæsj',
    'drop': 'dråpe',
    'drops': 'dråper',
    'rings': 'ringer',
    'ring': 'ring',
    'chunks': 'biter',
    'chunk': 'bit',
    'strip': 'strimmel',
    'strips': 'strimler',
    'cube': 'terning',
    'cubes': 'terninger',

    # === Time ===
    'min': 'min',
    'mins': 'min',
    'sec': 'sek',
    'secs': 'sek',
    'day': 'dag',
    'days': 'dager',
    'week': 'uke',
    'weeks': 'uker',

    # === Adjectives ===
    'fresh': 'fersk',
    'frozen': 'frossen',
    'dried': 'tørket',
    'raw': 'rå',
    'cooked': 'kokt',
    'clean': 'ren',
    'small': 'liten',
    'large': 'stor',
    'medium': 'middels',
    'big': 'stor',
    'tiny': 'liten',
    'soft': 'myk',
    'hard': 'hard',
    'tender': 'mør',
    'crunchy': 'sprø',
    'crispy': 'sprø',
    'smooth': 'jevn',
    'thick': 'tykk',
    'thin': 'tynn',
    'even': 'jevn',
    'golden': 'gyllen',
    'brown': 'brun',
    'green': 'grønn',
    'red': 'rød',
    'yellow': 'gul',
    'white': 'hvit',
    'black': 'sort',
    'dark': 'mørk',
    'light': 'lys',
    'sweet': 'søt',
    'sour': 'sur',
    'salty': 'salt',
    'spicy': 'krydret',
    'warm': 'varm',
    'hot': 'varm',
    'cold': 'kald',
    'cool': 'kjølig',
    'room temperature': 'romtemperatur',

    # === Small words ===
    # Don't translate 'the' / 'a' / 'an' — Norwegian uses definite suffixes
    # and my word-level substitution can't rewrite endings reliably.
    # Leaving them in English is ugly but better than grammatically broken.
    'is': 'er',
    'are': 'er',
    'was': 'var',
    'were': 'var',
    'will': 'skal',
    'would': 'vil',
    'should': 'bør',
    'can': 'kan',
    'could': 'kunne',
    'may': 'kan',
    'might': 'kan',
    'must': 'må',
    'need': 'trenger',
    'needs': 'trenger',
    'want': 'vil ha',
    'it': 'det',
    'its': 'dens',
    'this': 'denne',
    'these': 'disse',
    'that': 'som',
    'those': 'de',
    'you': 'du',
    'your': 'din',
    # Intentionally NOT mapping 'i' -> 'jeg' — causes a cascade bug where
    # previously-substituted "in → i" becomes "i → jeg". Recipes rarely use
    # first-person "I" anyway.
    'we': 'vi',
    'they': 'de',
    'them': 'dem',
    'their': 'deres',
    'gently': 'forsiktig',
    'carefully': 'forsiktig',
    'quickly': 'raskt',
    'slowly': 'sakte',
    'gradually': 'gradvis',
    'thoroughly': 'grundig',
    'well': 'godt',
    'evenly': 'jevnt',
    'remaining': 'resterende',
    'rest of': 'resten av',
    'rest': 'resten',
    'except': 'bortsett fra',
    'except the': 'bortsett fra',
    'dissolve': 'løs opp',
    'dissolved': 'oppløst',
    'absorb': 'absorber',
    'absorbed': 'absorbert',
    'pour in': 'hell i',
    'turn up': 'skru opp',
    'turn down': 'skru ned',
    'turn on': 'skru på',
    'turn off': 'skru av',
    'increase': 'øk',
    'decrease': 'reduser',
    'reduce': 'reduser',
    'reduced': 'redusert',
    'speed': 'hastighet',
    'machine': 'maskin',
    'blender': 'blender',
    'mixer': 'mikser',
    'kitchen': 'kjøkken',
    'kitchen towel': 'kjøkkenhåndkle',
    'spices': 'krydder',
    'spice': 'krydder',
    'ice cream scooper': 'iskremskje',
    'option 1': 'alternativ 1',
    'option 2': 'alternativ 2',
    'the machine': 'maskinen',
    'the water': 'vannet',
    'the dough': 'deigen',
    'the oven': 'ovnen',
    'the pot': 'kjelen',
    'the pan': 'pannen',
    'the bowl': 'bollen',
    'the salt': 'saltet',
    'the oil': 'oljen',
    'the onion': 'løken',
    'the onions': 'løkene',
    'the garlic': 'hvitløken',
    'the mixture': 'blandingen',
    'the rest': 'resten',
    'the ingredients': 'ingrediensene',
    'dry ingredients': 'tørre ingredienser',
    'wet ingredients': 'våte ingredienser',
    'finely': 'fint',
    'coarsely': 'grovt',
    'along': 'sammen',
    'along with': 'sammen med',
    'coat': 'dekk',
    'coated': 'dekket',
    'fat': 'fett',
    'translucent': 'blanke',
    'translusent': 'blanke',
    'few': 'få',
    'a few': 'noen få',
    'little': 'litt',
    'a little': 'litt',
    'more': 'mer',
    'less': 'mindre',
    'enough': 'nok',
    'any': 'noen',
    'there': 'der',
    'here': 'her',
    'now': 'nå',
    'again': 'igjen',
    'once': 'når',
    'twice': 'to ganger',
    'piece by piece': 'stykke for stykke',
    'inside': 'innsiden',
    'outside': 'utsiden',
    'top': 'toppen',
    'bottom': 'bunnen',
    'middle': 'midten',
    'on top': 'på toppen',
    'at the bottom': 'i bunnen',
    'edge': 'kant',
    'edges': 'kanter',
    'corner': 'hjørne',
    'surface': 'overflate',
    'consistency': 'konsistens',
    'texture': 'tekstur',
    'flavor': 'smak',
    'flavour': 'smak',
    'taste of': 'smak av',
    'smell': 'lukt',
    'aroma': 'aroma',
    'juice': 'saft',
    'zest': 'skall',
    'skin': 'skinn',
    'shell': 'skall',
    'juicy': 'saftig',
    'sticky': 'klissete',
    'creamy': 'kremet',
    'fluffy': 'luftig',
    'firm': 'fast',
    'loose': 'løs',
    'runny': 'flytende',
    'liquid': 'væske',
    'solid': 'fast',
    'powder': 'pulver',
    'whole': 'hel',
    'half': 'halv',
    'quarter': 'kvart',
    'quarters': 'kvarte',
    'third': 'tredje',
    'double': 'dobbelt',
    'triple': 'trippel',
    'separate': 'separat',
    'separately': 'separat',
    'together': 'sammen',
    'apart': 'fra hverandre',
    'pot of water': 'kjele med vann',
    'large pot of water': 'stor kjele med vann',
    'before adding': 'før du tilsetter',
    'after adding': 'etter at du har tilsatt',
    'slightly': 'litt',
    'another': 'en ny',
    'allow': 'la',
    'allow the': 'la',
    'release': 'frigjøre',
    'release their': 'frigjøre sine',
    'flavors': 'smaker',
    'flavours': 'smaker',
    'flavor': 'smak',
    'flavour': 'smak',
    'depending on': 'avhengig av',
    'according to': 'ifølge',
    'towards the end': 'mot slutten',
    'a separate': 'en separat',
    'a little': 'litt',
    'a bit': 'litt',
    'a splash': 'en skvett',
    'a cup': 'en kopp',
    'a dash': 'en dæsj',
    'a pot': 'en kjele',
    'a bowl': 'en bolle',
    'a blender': 'en blender',
    'a spoon': 'en skje',
    'a fork': 'en gaffel',
    'a knife': 'en kniv',
    'a jar': 'et glass',
    'a time': 'gangen',
    'at a time': 'av gangen',
    'dough is': 'deigen er',
    'once the': 'når',
    'when the': 'når',
    'when it': 'når det',
    'it is': 'det er',
    'you can': 'du kan',
    'be careful': 'vær forsiktig',
    'if you': 'hvis du',
    'as desired': 'etter ønske',
    'as possible': 'som mulig',
    'as well': 'også',
    'as well as': 'samt',
    'by hand': 'for hånd',
    'at room temperature': 'ved romtemperatur',
    'room temperature': 'romtemperatur',
    'to taste': 'etter smak',
    'if you want': 'hvis du vil',
    'fork': 'gaffel',
    'poke holes': 'stikk hull',
    'prick': 'prikk',
    'see the': 'se',
    'bake through': 'gjennomstek',
    'baked through': 'gjennomstekt',
    'cook through': 'gjennomkok',
    'cooked through': 'gjennomkokt',
    'not brown': 'ikke brune',
    'don\'t brown': 'ikke brune',
    'do not brown': 'ikke brune',
    'be': 'være',
    'being': 'være',
    'been': 'vært',
    'doing': 'gjør',
    'done': 'ferdig',
    'went': 'gikk',
    'going': 'gå',
    'gone': 'gått',
    'came': 'kom',
    'come': 'kom',
    'coming': 'kommende',
    'give': 'gi',
    'gave': 'ga',
    'giving': 'gir',
    'given': 'gitt',
    'get': 'få',
    'got': 'fikk',
    'getting': 'får',
    'gotten': 'fått',
    'take': 'ta',
    'taken': 'tatt',
    'taking': 'tar',
    'took': 'tok',
    'make': 'lag',
    'made': 'laget',
    'making': 'laging',
    'see': 'se',
    'saw': 'så',
    'seen': 'sett',
    'know': 'vet',
    'known': 'kjent',
    'knew': 'visste',
    'try': 'prøv',
    'tried': 'prøvde',
    'trying': 'prøver',
    'find': 'finn',
    'found': 'fant',
    'finding': 'finner',
    'show': 'vis',
    'showed': 'viste',
    'shown': 'vist',
    'look': 'se',
    'looked': 'så',
    'looking': 'ser',
    'save': 'lagre',
    'saved': 'lagret',
    'saving': 'lagring',
    'help': 'hjelp',
    'helped': 'hjulpet',
    'helping': 'hjelp',
    'work': 'arbeid',
    'worked': 'arbeidet',
    'working': 'arbeider',
    'prepare': 'forbered',
    'prepared': 'forberedt',
    'preparing': 'forberedelse',
    'prep': 'forbered',
    'prepping': 'forberedelse',
    'store': 'oppbevar',
    'stored': 'oppbevart',
    'storing': 'oppbevaring',
    'last': 'hold',
    'lasting': 'holdbarhet',
    'lasted': 'holdt',
    'batch': 'porsjon',
    'round': 'runde',
    'right': 'høyre',
    'left': 'venstre',
    'ball': 'ball',
    'balls': 'baller',
    'round balls': 'runde baller',
    'flat': 'flat',
    'flat side': 'flat side',
    'rounded': 'rundet',
    'hole': 'hull',
    'holes': 'hull',
    'oil the': 'smør med olje',
    'greased': 'smurt',
    'grease': 'smør',
    'some': 'litt',
    'any': 'noe',
    'all': 'alle',
    'both': 'begge',
    'each': 'hver',
    'every': 'hver',
    'no': 'ikke',
    'not': 'ikke',
    'yes': 'ja',
    'very': 'veldig',
    'just': 'bare',
    'only': 'kun',
    'also': 'også',
    'too': 'også',
    'as': 'som',
    'at': 'på',
    'by': 'av',
    'from': 'fra',
    'for': 'i',
    'of': 'av',
    'in': 'i',
    'on': 'på',
    'to': 'til',
    'up': 'opp',
    'down': 'ned',
    'out': 'ut',
    'off': 'av',
    'into': 'i',
    'onto': 'på',
    'over': 'over',
    'under': 'under',
    'between': 'mellom',
    'through': 'gjennom',
    'throughout': 'gjennom',
    'during': 'under',
    'while': 'mens',
    'until': 'til',
    'before': 'før',
    'after': 'etter',
    'when': 'når',
    'where': 'hvor',
    'how': 'hvordan',
    'why': 'hvorfor',
    'if': 'hvis',
    'because': 'fordi',
    'so': 'så',
    'but': 'men',
    'however': 'imidlertid',
    'instead': 'i stedet',
    'rather': 'heller',
    'quite': 'ganske',
    'really': 'virkelig',
    'even': 'selv',
    'maybe': 'kanskje',
    'perhaps': 'kanskje',
    'usually': 'vanligvis',
    'normally': 'normalt',
    'always': 'alltid',
    'often': 'ofte',
    'sometimes': 'noen ganger',
    'rarely': 'sjelden',
    'never': 'aldri',
    'make sure': 'sørg for',
    'be sure': 'vær sikker på',
    'keep': 'hold',
    'keeping': 'oppbevaring',
    'kept': 'holdt',
    'form a': 'form en',
    'look like': 'ser ut som',
}


# Precompile step patterns once at module load for speed.
_STEP_PHRASES_COMPILED = [
    (re.compile(p, re.IGNORECASE), r) for p, r in STEP_PHRASES
]

# Build a single big alternation regex so substitutions happen in ONE pass
# (avoids the cascade bug where "in" -> "i" then "i" -> "jeg").
# Longest keys first so multi-word phrases match before their sub-words.
_SORTED_STEP_KEYS = sorted(STEP_WORDS.keys(), key=len, reverse=True)
_STEP_LOOKUP = {k.lower(): STEP_WORDS[k] for k in _SORTED_STEP_KEYS}
_STEP_MEGA = re.compile(
    r'(?<![A-Za-zÆØÅæøå])(' +
    '|'.join(re.escape(k) for k in _SORTED_STEP_KEYS) +
    r')(?![A-Za-zÆØÅæøå])',
    re.IGNORECASE,
)


def _step_replace(m):
    key = m.group(1).lower().strip()
    return _STEP_LOOKUP.get(key, m.group(1))


def _capitalize_sentences(text):
    """Capitalize first letter of each sentence (including start of string)."""
    if not text:
        return text
    # Capitalize after . ! ? and at start
    def cap(m):
        return m.group(1) + m.group(2).upper()
    # Start of string
    text = re.sub(r'^(\s*)([a-zæøå])', cap, text)
    # After sentence-ending punctuation + whitespace
    text = re.sub(r'([.!?]\s+)([a-zæøå])', cap, text)
    return text


def translate_step(text):
    """Translate a single step. Phrase patterns first, then word-level."""
    if not text:
        return text

    t = text.strip()

    # Try full-sentence phrase patterns first
    for pattern, replacement in _STEP_PHRASES_COMPILED:
        if pattern.match(t):
            return _capitalize_sentences(pattern.sub(replacement, t))

    # Single-pass word-level substitution (no cascading).
    out = _STEP_MEGA.sub(_step_replace, t)
    return _capitalize_sentences(out)


def translate_ingredient(ing):
    name = (ing.get('name') or '').strip()
    unit = (ing.get('unit') or '').strip()
    no_name = INGREDIENTS.get(name, name)
    # Some names we miss — try lowercase key
    if no_name == name and name.lower() in [k.lower() for k in INGREDIENTS]:
        for k, v in INGREDIENTS.items():
            if k.lower() == name.lower():
                no_name = v
                break
    no_unit = UNIT_MAP.get(unit, unit)
    return {
        'quantity': ing.get('quantity', 0),
        'unit': no_unit,
        'name': no_name,
    }


def translate_title(title):
    # Try direct, then strip unicode apostrophe variants
    if title in TITLES:
        return TITLES[title]
    # Try with straight apostrophes
    alt = title.replace('\u00b4', "'").replace('\u2019', "'")
    if alt in TITLES:
        return TITLES[alt]
    alt2 = title.replace("'", '\u00b4')
    if alt2 in TITLES:
        return TITLES[alt2]
    return title  # fall back to English


def translate_recipe(r):
    en_ings = r.get('ingredients', [])
    en_steps = r.get('steps', [])
    en_desc = r.get('description') or ''

    rid = r.get('id')
    override = STEP_OVERRIDES.get(rid)
    if override is not None and len(override) == len(en_steps):
        no_steps = list(override)
    else:
        no_steps = [translate_step(s) for s in en_steps]

    no = {
        'title': translate_title(r['title']),
        'description': translate_step(en_desc) if en_desc else '',
        'ingredients': [translate_ingredient(i) for i in en_ings],
        'steps': no_steps,
    }
    return no


def main():
    d = json.load(open(SRC, encoding='utf-8'))

    done = 0
    preserved = 0
    missing_titles = []
    missing_ingredients = set()

    for r in d['recipes']:
        manual = r.get('translations') or {}
        if manual.get('no'):
            preserved += 1
            continue

        no = translate_recipe(r)
        r['translations'] = {**manual, 'no': no}
        done += 1

        # Track what we failed to translate
        if no['title'] == r['title'] and r['title'] not in TITLES:
            missing_titles.append(r['title'])
        for en, n in zip(r.get('ingredients', []), no['ingredients']):
            en_name = (en.get('name') or '').strip()
            no_name = (n.get('name') or '').strip()
            if en_name and en_name == no_name and en_name not in INGREDIENTS:
                missing_ingredients.add(en_name)

    # Update pack metadata
    d['id'] = 'fredheim-recepies-with-pictures'
    d['name'] = 'Fredheim recepies with pictures'
    d['description'] = 'A selection of Fredheim recipes bundled with photos.'
    d['author'] = 'Fredheim'
    d['version'] = '1.6.0'
    d['tags'] = ['fredheim', 'with-photos']

    # Category translations on each recipe — we keep English category key
    # because category is used as a lookup key elsewhere, but we could set
    # translations for display. For now just leave as-is; the category is
    # rendered via i18n.

    with open(DST, 'w', encoding='utf-8') as f:
        json.dump(d, f, ensure_ascii=False, indent=2)

    total_translated = sum(
        1 for r in d['recipes'] if r.get('translations', {}).get('no')
    )
    override_hits = sum(
        1 for r in d['recipes']
        if r.get('id') in STEP_OVERRIDES and not (
            (r.get('translations') or {}).get('no', {}).get('_preserved')
        )
    )
    print(f'Newly translated: {done}')
    print(f'Preserved manual: {preserved}')
    print(f'Step overrides available: {len(STEP_OVERRIDES)}')
    print(f'Recipes matched by step override: {override_hits}')
    print(f'Total with NO translations: {total_translated}/{len(d["recipes"])}')
    print(f'Images preserved: {sum(1 for r in d["recipes"] if r.get("imageUrl"))}')
    if missing_titles:
        print(f'\nTitles not in dictionary ({len(missing_titles)}):')
        for t in missing_titles:
            print(f'  {t}')
    if missing_ingredients:
        print(f'\nIngredient names not in dictionary ({len(missing_ingredients)}):')
        for i in sorted(missing_ingredients):
            print(f'  {i}')


if __name__ == '__main__':
    main()
